"""Fallback for `campaign_db.snapshot_ad_stats` when the ledger is not on the path.

Batch B owns `campaign_db.py` in the `campaign-ledger` repo, which this session
cannot see or write to. Rather than let `pull_ad_stats.py` be unrunnable and
untestable until that repo lands, the import is defensive and falls back to
this: same call, same row shape, written to a JSONL file instead of Postgres,
and it says loudly that the ledger is not connected.

The rows written here are not a substitute for the ledger. They exist so that a
day's numbers are not lost if the pull runs before the ledger is wired, and so
the tests can assert on real output.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

log = logging.getLogger("ad_stats")

DEFAULT_PATH = Path(__file__).resolve().parent / "out" / "ad_stats.jsonl"

# The exact column list for campaign.ad_stats, fixed by Batch B's schema.
# `id` is generated by the database, so it is never written from here.
COLUMNS = (
    "campaign_name",
    "ad_set_name",
    "creative_content_id",
    "captured_on",
    "spend_eur",
    "impressions",
    "clicks",
    "leads",
)


def snapshot_ad_stats(row: dict, path: Path | None = None) -> dict:
    """Append one campaign.ad_stats row to a JSONL file.

    Deliberately mirrors the ledger function's name and single-row shape so that
    swapping the real one in is an import change and nothing else.
    """
    unknown = set(row) - set(COLUMNS)
    if unknown:
        raise ValueError(f"columns not in campaign.ad_stats: {sorted(unknown)}")
    missing = set(COLUMNS) - set(row)
    if missing:
        raise ValueError(f"missing campaign.ad_stats columns: {sorted(missing)}")

    target = Path(path) if path else DEFAULT_PATH
    target.parent.mkdir(parents=True, exist_ok=True)
    with target.open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(row, sort_keys=True) + "\n")
    return row
