"""Bind this repo's ad_stats rows against Batch B's real `campaign_db`.

The sibling test that `outreach-engine` and `reel-engine` both have and this repo
did not. It exists because the two defects found on 2026-09-08 were *both*
invisible from inside this repo:

  * `creative_content_id` carried a slug like `v5-pilot` into a column Batch B
    declares `uuid references campaign.content (id)`. Every offline test passed,
    because `report/ledger_shim.py` accepts any string. Postgres would have
    rejected it on the first live write.
  * Ad-level rows collided on `unique (campaign_name, ad_set_name, captured_on)`
    and `snapshot_ad_stats` upserts on that key - a replace, not a sum - so 39%
    of the fixture's spend disappeared without an error.

Neither is a bug in this repo's logic. Both are disagreements with a module this
repo cannot import at build time. That is exactly what a contract test is for,
and why the assertions below bind against B's *real* signature rather than a
local stub.

Follows the same idiom as the sibling repos: locate `campaign_db.py` by file
path, and SKIP rather than fail when campaign-ledger is not checked out beside
this repo, so a developer with only this repo still gets a green suite.
"""

import importlib.util
import inspect
import os
import sys
import uuid
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from report import ledger_shim                                    # noqa: E402
from report.pull_ad_stats import (                                # noqa: E402
    LEDGER_COLUMNS,
    aggregate,
    creative_content_id,
    ledger_row,
    load_fixture,
    transform,
)

ROOT = Path(__file__).resolve().parents[1]


def _campaign_db_path():
    override = os.environ.get("CAMPAIGN_DB_PATH")
    candidates = [Path(override)] if override else []
    candidates += [
        ROOT.parent / "campaign-ledger" / "src" / "campaign_db.py",
        ROOT.parent / "campaign-ledger" / "campaign_db.py",
    ]
    return next((p for p in candidates if p.is_file()), None)


@pytest.fixture(scope="module")
def campaign_db():
    """Batch B's real client, imported by file path.

    Skipped, not failed, when campaign-ledger is not checked out beside this
    repo. Set CAMPAIGN_DB_PATH to point at it from anywhere else.
    """
    path = _campaign_db_path()
    if path is None:
        pytest.skip("campaign-ledger is not checked out beside this repo; "
                    "set CAMPAIGN_DB_PATH to run the contract tests")
    spec = importlib.util.spec_from_file_location("_batch_e_campaign_db", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _rows():
    return aggregate(transform(load_fixture()))


# --- the signature ----------------------------------------------------------

def test_every_row_binds_to_batch_bs_signature(campaign_db):
    """The whole point of this file."""
    sig = inspect.signature(campaign_db.snapshot_ad_stats)
    for row in _rows():
        sig.bind(**ledger_row(row))


def test_ledger_columns_are_exactly_what_b_accepts(campaign_db):
    """A column this repo invents is a TypeError on the day the ledger lands."""
    accepted = {
        name for name, p in
        inspect.signature(campaign_db.snapshot_ad_stats).parameters.items()
        if p.kind is not p.VAR_KEYWORD
    }
    assert set(LEDGER_COLUMNS) <= accepted, (
        f"this repo sends columns B does not accept: {set(LEDGER_COLUMNS) - accepted}"
    )


def test_batch_b_has_no_id_parameter(campaign_db):
    """`id` is generated by the database and must never be sent."""
    params = inspect.signature(campaign_db.snapshot_ad_stats).parameters
    assert "id" not in params


def test_the_shim_and_the_real_client_agree_on_the_columns(campaign_db):
    """If they drift, offline runs stop predicting live ones."""
    accepted = {
        name for name, p in
        inspect.signature(campaign_db.snapshot_ad_stats).parameters.items()
        if p.kind is not p.VAR_KEYWORD
    }
    assert set(ledger_shim.COLUMNS) <= accepted


# --- the two defects, as regressions ----------------------------------------

def test_no_row_carries_a_non_uuid_creative_id(campaign_db):
    """Defect 1. The shim accepts any string; Postgres does not.

    campaign.ad_stats.creative_content_id is `uuid references campaign.content
    (id)`, so a human label like `v5-pilot` fails the insert outright.
    """
    for row in _rows():
        value = ledger_row(row)["creative_content_id"]
        assert value is None or uuid.UUID(value)


def test_the_shape_sent_before_the_fix_would_not_have_been_a_uuid():
    """Guards the guard: proves the old shape really was invalid.

    Without this, the test above would keep passing if the extractor were
    changed to always return None for an unrelated reason, and the regression it
    documents would quietly stop being tested.
    """
    label = creative_content_id("teams_q4 | v5-pilot | s05-two-weeks-4x5")
    assert label == "v5-pilot"
    with pytest.raises(ValueError):
        uuid.UUID(label)


def test_no_two_rows_share_batch_bs_natural_key(campaign_db):
    """Defect 2. B upserts on (campaign_name, ad_set_name, captured_on),
    replacing rather than summing, so two rows sharing that key mean the second
    silently overwrites the first."""
    keys = [
        (r["campaign_name"], r["ad_set_name"], r["captured_on"])
        for r in (ledger_row(x) for x in _rows())
    ]
    assert len(keys) == len(set(keys))


def test_aggregation_loses_no_spend_on_the_way_to_the_ledger(campaign_db):
    """The money assertion, stated against what actually reaches B."""
    raw = transform(load_fixture())
    sent = [ledger_row(r) for r in _rows()]
    assert sum(r["spend_eur"] for r in sent) == pytest.approx(
        sum(r.spend_eur for r in raw))


# --- types --------------------------------------------------------------------

def test_the_numeric_columns_arrive_as_numbers(campaign_db):
    for r in (ledger_row(x) for x in _rows()):
        assert isinstance(r["spend_eur"], (int, float))
        for field in ("impressions", "clicks", "leads"):
            assert isinstance(r[field], int)


def test_captured_on_survives_batch_bs_day_normaliser(campaign_db):
    """B calls `_day()` on it. Whatever this repo sends has to be accepted."""
    for r in (ledger_row(x) for x in _rows()):
        assert campaign_db._day(r["captured_on"]) == r["captured_on"]
